name: LoginPage

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npx playwright install
      - run: npm install --save-dev allure-playwright allure-commandline
      - run: npx playwright test --reporter=allure-playwright
      - run: npx allure generate ./allure-results -o ./allure-report --clean
